### ISSUE TITLE
Siri stops working

### ISSUE THREAD

**Issue by thiagodebastos** [mathiasbynens/dotfiles#690]
I've been looking around for how to re-enable siri but can't find anything so far. What would affect siri in MacOS Sierra? 

Currently, clicking on the Siri icon in the menu bar does not do anything.

**Comment by thiagodebastos** [comment]
I resolved the issue by diving into `~/Library`. I found `com.apple.Siri.plist` in `~/Library/Preferences` and deleted it. I then disabled and re-enabled Siri from the system preferences, which results in a new `.plist` file being created and the issue is now resolved.

**Comment by paulwithap** [comment]
Unfortunately this didn't fix my Siri issues. Anyone else unable to get Siri to work while using these dotfiles?

**Comment by paulwithap** [comment]
...and this solved it for me: https://discussions.apple.com/thread/7679080?start=0&tstart=0

**Comment by jooray** [comment]
This helped me too, but that reenables notification center, which I don't particularly like.
